### PR TITLE
Fix Deploy Script & Deploy to Optimistic Goerli

### LINKED ISSUE #174: Set KWENTA on SupplySchedule in deploy script

### LINKED ISSUE #175: Set TreasuryDAO on RewardEscrow in deploy script

### PR DESCRIPTION
**Pull request by JChiaramonte7**
Resolves #175 
Resolves #174

### CODE REVIEW

File: scripts/deploy.ts [hunk 1]
```diff
@@ -59,6 +58,13 @@ async function main() {
         await kwenta.supplySchedule()
     );
 
+    // set KWENTA address in SupplySchedule
+    await supplySchedule.setKwenta(kwenta.address);
+    console.log(
+        "SupplySchedule: Kwenta address set to:  ",
+        await supplySchedule.kwenta()
+    );
+
```
Comment (JChiaramonte7) [inline scripts/deploy.ts:67]: #174

File: scripts/deploy.ts [hunk 2]
```diff
@@ -73,6 +79,14 @@ async function main() {
...
     );
 
+    // set StakingRewards address in RewardEscrow
+    await rewardEscrow.setTreasuryDAO(TREASURY_DAO);
+    console.log(
+        "RewardEscrow: TreasuryDAO address set to:    ",
+        await rewardEscrow.treasuryDAO()
+    );
+    console.log("✅ Setters set!");
+
```
Comment (JChiaramonte7) [inline scripts/deploy.ts:89]: #175

File: scripts/testnet/deploy-vKWENTA-goerli.ts [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+    );
+
+    await vKwenta.deployed();
+    await saveDeployments("vKwenta", vKwenta);
+    await verify(
+        vKwenta.address,
+        [
+            "vKwenta",
+            "vKWENTA",
+            "0xC2ecD777d06FFDF8B3179286BEabF52B67E9d991", //treasury
```
[the remark this answers is not in the document]
Comment (JChiaramonte7) [reply scripts/testnet/deploy-vKWENTA-goerli.ts:40]: Yes
